version: "3.7"
services:

  oracle-database:
    image: jplarochedocker/custom-oracle:latest
    ports:
      - target: 1521
        published: 1521
        protocol: tcp
        mode: host
      - target: 8080
        published: 8080
        protocol: tcp
        mode: host
    volumes:
      - type: tmpfs
        target: /dev/shm
        tmpfs:
          size: 1073741824 # this means 1GB
    networks:
      - striim_oracle_net
    environment:
      ORACLE_PWD: "tiger"

  striim:
    build:
      context: .
      dockerfile: Dockerfile.striim
    image: custom-striim:latest
    ports:
      - target: 9080
        published: 80
        protocol: tcp
        mode: host
    networks:
      - striim_oracle_net
    environment:
      STRIIM_ACCEPT_EULA: "Y"
    extra_hosts:
    - "zoo1:10.255.0.6"
    - "zoo2:10.255.0.7"
    - "zoo3:10.255.0.8"

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=10.255.1.3
    ports:
    - "8081:8081"

networks:
  striim_oracle_net:
    driver: overlay

